CREATE TABLE IF NOT EXISTS  `images` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `imgPath` VARCHAR(100) NOT NULL,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;